### ISSUE TITLE
Audio recorder sometimes doesn't work.

### ISSUE THREAD

**Issue by supreethms** [PixelExperience-Devices/device_oneplus_msm8998-common#4]
Build zip name: QQ3A.200605.001
PixelExperience_Plus_cheeseburger-10.0-20200624-2028-OFFICIAL

What happened: Sometimes on call, the audio just doesn't work. I can hear what the other person says. But the audio from my phone isn't reaching the other person. Happened with the current build and the previous one.

Clean flashed: Yes

Changed Kernel: No

Modules installed: None
[Log_2020-06-30_10-36-01.txt](https://github.com/PixelExperience-Devices/device_oneplus_msm8998-common/files/4849598/Log_2020-06-30_10-36-01.txt)

**Comment by itsjoeoui** [comment]
Disable voice match if you are having mic problem
